### ISSUE TITLE
Doesn't look inside user files

### ISSUE THREAD

**Issue by edalzell** [swiftmade/statamic-clear-assets#14]
Running this on a huge site I noticed that it is removing assets that are referenced in the user .yaml files.

![CleanShot 2024-01-30 at 15 26 11@2x](https://github.com/swiftmade/statamic-clear-assets/assets/6069653/86c5133d-1648-4473-99bc-273b5f6a5590)

**Comment by mmodler** [comment]
Did you try adjusting the config?

```
    'scan_folders' => [
        'content',
        'users',
    ],
```

**Comment by aozisik** [comment]
Hi @edalzell 

I released a new version that includes `users` directory in the scan_folders by default. If you have published the config file into your codebase, you can update it like @mmodler suggested.

Alternatively, 
- you can ignore the `avatars` container itself using the `ignore_containers` config,
- or if it's not a separate asset container you can use the `ignore_filenames` config by adding a glob like this: `avatars/*`.

If you want to publish and modify the config file, use:

```bash
 php artisan vendor:publish --tag=statamic-clear-assets-config
 ```

Hope this helps!
