### ISSUE TITLE
Add a force option to allow deletion without user confirmation

### ISSUE THREAD

**Issue by CedsTrash** [swiftmade/statamic-clear-assets#18]
Hi,

I'm pretty confident about the assets I'm not using and I'd like to run `php please assets:clear` with Laravel Scheduler, or as part as a deployment script.

It would be great to have the ability to execute the command without any interaction.

Thanks.

**Comment by aozisik** [comment]
Done :) You can have the command run without asking for confirmation by adding the `--force=1` flag at the end.

**Comment by CedsTrash** [comment]
That's great news! Thank you!
