### ISSUE TITLE
FR: Choose asset container

### ISSUE THREAD

**Issue by helloDanuk** [swiftmade/statamic-clear-assets#7]
Thanks for this addon. It's a nice little helper!

It might be a good addition if you first choose which asset container the addon should check for unused assets.

Idea behind: I have a container with client access and a 'super user'-container where I upload favicons, helper-pdf, custom cms logo etc. Running `php please assets:clear` lists these as unused, maybe because they are harcoded or used outside of the website.

I would like to clean up only the container with client access because clients tend to upload the same image a dozen times 🙄…

**Comment by aozisik** [comment]
Hi @helloDanuk,

Sounds like your issue is related to #6. We'll look into making the scanned assets and content paths configurable.

**Comment by aozisik** [comment]
@helloDanuk It is now possible to configure this as of v1.2.0.
https://github.com/swiftmade/statamic-clear-assets/releases/tag/v1.2.0

**Comment by helloDanuk** [comment]
Thanks for the new config options. They will be helpful.
